import { ReactNode } from "react";
import type { Metadata } from "next";
import "./globals.css";

import { Poppins } from "next/font/google";
import { Inter } from "next/font/google";

import Header from "@/components/header/Header";

const poppins = Poppins({
  weight: ["400", "500", "700"],
  variable: "--font-poppins",
});

const inter = Inter({
  weight: ["400"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Cryptozen",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${inter.variable} font-poppins bg-black antialiased min-h-screen`}
      >
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
};

export default RootLayout;
